name: Code Check

on: push

defaults:
  run:
    working-directory: ./src

jobs:
  fix-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run PHP CS Fixer
        uses: docker://oskarstark/php-cs-fixer-ga
      - name: Run Prettier
        run: npm run format
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "style: adjust code style"
          branch: ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}